all: santa twtr impr

santa: santa.cpp
	g++ -std=c++11 -Wall -O3 santa.cpp -o apps/app
	
twtr: twtr.cpp
	g++ -std=c++11 -Wall -O3 twtr.cpp -o apps/twtr

impr: impr.cpp
	g++ -std=c++11 -Wall -O3 impr.cpp -o apps/impr
	
clean:
	rm apps/*